# Execute your favorite apps at launch
exec-once = waybar
exec-once = dunst
exec-once = wlsunset -l 37 -L -121 -t 2000
exec-once = swww-daemon
exec-once = hypridle
exec-once = flatpak run md.obsidian.Obsidian
# Load configuration from ML4W Hyprland Settings App
exec = ~/.config/ml4w-hyprland-settings/hyprctl.sh
