# See https://wiki.hyprland.org/Configuring/Variables/ for more
general {
    gaps_in = 2
    gaps_out = 2
    border_size = 2
    col.active_border = rgb(d4be98)
    col.inactive_border = rgb(45403d)
    layout = dwindle
    resize_on_border = true
}
