# See https://wiki.hyprland.org/Configuring/Monitors/
monitor=DP-2,1920x1080,auto,1
monitor=HDMI-A-1,1920x1080,auto,1

$m2 = DP-2
$m1 = HDMI-A-1

# Create persistent workspaces 1-10
workspace = 1, monitor:$m1
workspace = 2, monitor:$m1
workspace = 3, monitor:$m1
workspace = 4, monitor:$m1
workspace = 5, monitor:$m1
workspace = 6, monitor:$m2
workspace = 7, monitor:$m2
workspace = 8, monitor:$m2
workspace = 9, monitor:$m2
workspace = 10, monitor:$m2